## r2dii.data and r2dii.match are now on CRAN: Demo and Q&A

This meetup is to bring attention the the newly-CRAN published packages `r2dii.data` and `r2dii.match`, the first two packages published as part of the `r2dii` suite. 

## Content
### How to find out what we have? 
* Where to keep an eye on all `r2dii` packages updates: [r2dii](https://2degreesinvesting.github.io/r2dii/index.html)
* In particular, new package releases and patch notes + author acknowledgements will be found on the `NEWS` tab

* Currently published packages on CRAN: [r2dii.data](https://CRAN.R-project.org/package=r2dii.data) and [r2dii.match](https://CRAN.R-project.org/package=r2dii.match)
* Package websites: [r2dii.data](https://2degreesinvesting.github.io/r2dii.data/) and [r2dii.match](https://2degreesinvesting.github.io/r2dii.match/)

### How to install and use?
Packages can now be installed as usual in R:
`install.packages("r2dii.data")`
`install.packages("r2dii.match")`

* Brief DEMO

### Discuss: What does it take to publish a package on CRAN?

## Resources
`./2020-03-31_r2dii-cran-demo/r2dii.data_demo.R`
`./2020-03-31_r2dii-cran-demo/r2dii.match_demo.R`
