---
title: "Checklist to review a pull request"
author: "Mauro Lepore"
output:
  github_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  comment = "#>",
  error = TRUE,
  collapse = TRUE
)
```

## master passes tests with no failures

```
git checkout master
```

```R
devtools::test()
```

## master passes checks with 0 errors, 0 warnings, 0 notes

```
git checkout master
```

```R
devtools::check()
```

## Package loads

```
git checkout pr
```

```R
devtools::load_all()
```

## Package passes tests

```R
devtools::test()
```

## Package passes checks with 0 errors, 0 warnings, and 0 notes

Some note may remain, but the number of errors warnings must be 0.

## Uses functions from other packages correctly

* Call `use_package()` to use packages (e.g. `use_package("dplyr")`).

And,

* Use `package::function` or `#' @importFrom package function` to use a specific function:

```R
f <- function(data) {
  dplyr::filter(data)
}

# Or

#' @importFrom dplyr filter
f <- function(data) {
  filter(data)
}
```

## Captures expected behavior in `#' @examples`

## Captures expected behavior in tests

## Captures expected behavior of exported functions in README

## Documents internal functions clearly enough

## Documents exported functions in full

## Connects similar documentation (e.g. via `@rdname`, `@seealso`, `@family`)

## pkgdown website builds
